server:
  port: 7100

---

spring:
  config:
    activate:
      on-profile: local
  r2dbc: 
    url: r2dbc:mariadb://localhost:7701/lessons-db
    username: lessons-user
    password: lessons-pwd-01

