server:
  port: 7200

---

spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:mariadb://localhost:7702/notations-db
    username: notations-user
    password: notations-pwd-01

